# Generated by Django 4.2.27 on 2026-02-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_blogpost_meta_description_blogpost_meta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='graphic_type',
            field=models.CharField(choices=[('CUBE', '3D Cyber Cube'), ('RING', 'Pulsing Tech Ring'), ('GLOBE', ' glowing Globe Icon'), ('IMAGE', 'Standard Image (Use Image URL)'), ('NONE', 'No Graphic (Text Only)')], default='CUBE', max_length=10),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='image_url',
            field=models.CharField(blank=True, help_text="Only used if 'Standard Image' is selected", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
