# Generated by Django 4.2.27 on 2026-02-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_heroslide_graphic_type_heroslide_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Agile Web', max_length=120)),
                ('tagline', models.CharField(default='Building digital ecosystems that scale.', max_length=220)),
                ('copyright_text', models.CharField(blank=True, help_text='Optional custom copyright line', max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('X', 'X (Twitter)'), ('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook')], max_length=20)),
                ('url', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('platform', 'url')},
            },
        ),
    ]
