# Generated by Codex on 2026-02-17

from django.db import migrations


def seed_footer_social(apps, schema_editor):
    FooterSettings = apps.get_model('main', 'FooterSettings')
    SocialLink = apps.get_model('main', 'SocialLink')

    if not FooterSettings.objects.exists():
        FooterSettings.objects.create(
            company_name='Agile Web',
            tagline='Building digital ecosystems that scale.',
            copyright_text='',
        )

    samples = [
        ('X', 'https://x.com/agileweb'),
        ('INSTAGRAM', 'https://www.instagram.com/agileweb'),
        ('FACEBOOK', 'https://www.facebook.com/agileweb'),
    ]

    for idx, (platform, url) in enumerate(samples, start=1):
        SocialLink.objects.get_or_create(
            platform=platform,
            url=url,
            defaults={'active': True, 'order': idx},
        )


def unseed_footer_social(apps, schema_editor):
    SocialLink = apps.get_model('main', 'SocialLink')
    sample_urls = [
        'https://x.com/agileweb',
        'https://www.instagram.com/agileweb',
        'https://www.facebook.com/agileweb',
    ]
    SocialLink.objects.filter(url__in=sample_urls).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_footersettings_sociallink'),
    ]

    operations = [
        migrations.RunPython(seed_footer_social, unseed_footer_social),
    ]
