# Generated by Django 4.2.27 on 2026-04-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_blogpost_author_name_blogpost_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
